# Generated by Django 5.2.11 on 2026-04-20 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended')], default='final', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=200)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier'], name='fhir_api_pr_identif_ffe2b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('arrived', 'Arrived'), ('in-progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('encounter_class', models.CharField(choices=[('AMB', 'Ambulatory'), ('IMP', 'Inpatient'), ('EMER', 'Emergency'), ('HH', 'Home Health'), ('VR', 'Virtual')], default='AMB', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='fhir_api.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='fhir_api.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='LOINC code', max_length=20)),
                ('display', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('partial', 'Partial'), ('preliminary', 'Preliminary'), ('final', 'Final')], default='final', max_length=20)),
                ('category', models.CharField(choices=[('LAB', 'Laboratory'), ('RAD', 'Radiology'), ('PAT', 'Pathology'), ('OTH', 'Other')], default='LAB', max_length=10)),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField()),
                ('conclusion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observations', models.ManyToManyField(blank=True, related_name='diagnostic_reports', to='fhir_api.observation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to='fhir_api.patient')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='fhir_api.encounter')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='fhir_api.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('booked', 'Booked'), ('arrived', 'Arrived'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('noshow', 'No Show')], default='booked', max_length=20)),
                ('appointment_type', models.CharField(choices=[('routine', 'Routine'), ('walkin', 'Walk-In'), ('checkup', 'Checkup'), ('followup', 'Follow-Up'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='fhir_api.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='fhir_api.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SNOMED or CPT code', max_length=20)),
                ('display', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preparation', 'Preparation'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('not-done', 'Not Done')], default='completed', max_length=20)),
                ('performed_date', models.DateTimeField()),
                ('body_site', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='fhir_api.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='fhir_api.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='fhir_api.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='AllergyIntolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='SNOMED code for substance', max_length=20)),
                ('display', models.CharField(help_text='Substance name', max_length=255)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('allergy_type', models.CharField(choices=[('allergy', 'Allergy'), ('intolerance', 'Intolerance')], default='allergy', max_length=20)),
                ('category', models.CharField(choices=[('food', 'Food'), ('medication', 'Medication'), ('environment', 'Environment'), ('biologic', 'Biologic')], default='medication', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('unable-to-assess', 'Unable to Assess')], default='low', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('reaction_description', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='fhir_api.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'clinical_status'], name='fhir_api_al_patient_2ba87c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ICD-10 or SNOMED code', max_length=20)),
                ('display', models.CharField(help_text='Human-readable name', max_length=255)),
                ('clinical_status', models.CharField(choices=[('active', 'Active'), ('recurrence', 'Recurrence'), ('relapse', 'Relapse'), ('inactive', 'Inactive'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('category', models.CharField(choices=[('problem-list-item', 'Problem List Item'), ('encounter-diagnosis', 'Encounter Diagnosis')], default='encounter-diagnosis', max_length=30)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('abatement_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='fhir_api.patient')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='fhir_api.encounter')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'clinical_status'], name='fhir_api_co_patient_2e0171_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_code', models.CharField(help_text='RxNorm or ATC code', max_length=20)),
                ('medication_display', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on-hold', 'On Hold'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('intent', models.CharField(choices=[('proposal', 'Proposal'), ('plan', 'Plan'), ('order', 'Order')], default='order', max_length=20)),
                ('dosage_text', models.CharField(blank=True, default='', max_length=255)),
                ('dosage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosage_unit', models.CharField(blank=True, default='', max_length=20)),
                ('frequency', models.CharField(blank=True, default='', help_text='e.g. 2 times/day', max_length=100)),
                ('authored_on', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_requests', to='fhir_api.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_requests', to='fhir_api.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_requests', to='fhir_api.practitioner')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'status'], name='fhir_api_me_patient_7c9034_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'period_start'], name='fhir_api_en_patient_6f3266_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreport',
            index=models.Index(fields=['patient', 'effective_date'], name='fhir_api_di_patient_e531df_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'start'], name='fhir_api_ap_patient_a1880e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['practitioner', 'start'], name='fhir_api_ap_practit_9935b9_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['patient', 'performed_date'], name='fhir_api_pr_patient_7a5966_idx'),
        ),
    ]
